# Generated by Django 5.1.2 on 2024-10-11 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'кошельки',
            },
        ),
    ]
